# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sonnh-instagram-feed"
client_id = "9c311bf9f43d5cadfed7a2b5775a8464"
application_url = "https://continually-neon-acting-replace.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://continually-neon-acting-replace.trycloudflare.com/auth/shopify/callback",
  "https://continually-neon-acting-replace.trycloudflare.com/authSa/shopify/callback",
  "https://continually-neon-acting-replace.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avada-first-app-store.myshopify.com"
